services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      docker-root-host: "${DOCKER_GATEWAY_HOST:-192.168.1.4}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  keycloak:
    container_name: keycloak
    depends_on:
     - kc_postgres
    ports:
      - 8080:8080
      #- 8443:8443
    build:
      dockerfile: ./keycloak/Dockerfile
    command:
      - "start-dev --proxy edge --hostname-strict=false"
      ##- "start-dev"
      #- "start"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: kc_postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      PROXY_ADDRESS_FORWARDING: true
      #KC_HOSTNAME: localhost
  kc_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  api:
    container_name: api
    depends_on:
      - mongo-db
    build:
        context: ./backend
        dockerfile: ./backend/Dockerfile
    ports:
      - 80:80
    environment:
      MONGO_URI: mongodb://mongo-db/Api
      PORT: 80
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017

